services:
  - type: web
    name: room-management-app
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: room-management-db
          property: connectionString
    autoDeploy: true

databases:
  - name: room-management-db
    databaseName: room_management
    user: room_user
    plan: free